theme: jekyll-theme-leap-day

title: Computing Education in Liberal Arts Colleges
description: Repositories for events and projects connected to the SIGCSE Committee on Computing Education in Liberal Arts Colleges
