remote_theme: pages-themes/leap-day@v0.2.0
plugins:
- jekyll-remote-theme

title: Computing Education in Liberal Arts Colleges
description: Repositories for events and projects connected to the SIGCSE Committee on Computing Education in Liberal Arts Colleges

show_downloads: false
