remote_theme: pages-themes/leap-day@v0.2.0
plugins:
- jekyll-remote-theme

title: Computing Education in Liberal Arts Colleges
description: Information, events and projects from the SIGCSE Committee on Computing Education in Liberal Arts Colleges

show_downloads: false
